/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        "surface-container": "#171f33",
        "secondary-container": "#00a572",
        "tertiary-fixed-dim": "#ffb2b7",
        "on-tertiary-fixed-variant": "#92002a",
        "tertiary-container": "#ff516a",
        outline: "#958ea0",
        "outline-variant": "#494454",
        "inverse-surface": "#dae2fd",
        "surface-container-lowest": "#060e20",
        "on-secondary-fixed-variant": "#005236",
        "secondary-fixed": "#6ffbbe",
        "on-secondary-fixed": "#002113",
        secondary: "#4edea3",
        "on-tertiary-fixed": "#40000d",
        "surface-bright": "#31394d",
        error: "#ffb4ab",
        "on-tertiary-container": "#5b0017",
        "on-error": "#690005",
        "inverse-on-surface": "#283044",
        "on-primary-fixed": "#23005c",
        "on-background": "#dae2fd",
        "on-error-container": "#ffdad6",
        "on-primary": "#3c0091",
        surface: "#0b1326",
        "on-surface-variant": "#cbc3d7",
        "primary-container": "#a078ff",
        "on-primary-fixed-variant": "#5516be",
        "primary-fixed-dim": "#d0bcff",
        "on-secondary": "#003824",
        "on-primary-container": "#340080",
        background: "#0b1326",
        "on-surface": "#dae2fd",
        "on-tertiary": "#67001b",
        "surface-container-highest": "#2d3449",
        tertiary: "#ffb2b7",
        "on-secondary-container": "#00311f",
        "surface-container-high": "#222a3d",
        "secondary-fixed-dim": "#4edea3",
        "primary-fixed": "#e9ddff",
        "surface-container-low": "#131b2e",
        "surface-tint": "#d0bcff",
        "inverse-primary": "#6d3bd7",
        primary: "#d0bcff",
        "surface-dim": "#0b1326",
        "tertiary-fixed": "#ffdadb",
        "error-container": "#93000a",
        "surface-variant": "#2d3449",
        warning: "#f5c84b",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "9999px",
      },
      spacing: {
        "container-max": "1280px",
        gutter: "24px",
        "margin-mobile": "16px",
        "margin-desktop": "40px",
        base: "8px",
      },
      maxWidth: {
        "container-max": "1280px",
      },
      fontFamily: {
        "display-lg": ["Montserrat", "sans-serif"],
        "display-lg-mobile": ["Montserrat", "sans-serif"],
        "label-caps": ["JetBrains Mono", "monospace"],
        "body-lg": ["Hanken Grotesk", "sans-serif"],
        "headline-md": ["Montserrat", "sans-serif"],
        "body-md": ["Hanken Grotesk", "sans-serif"],
      },
      fontSize: {
        "display-lg": ["48px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "800" }],
        "display-lg-mobile": ["32px", { lineHeight: "1.2", fontWeight: "800" }],
        "label-caps": ["12px", { lineHeight: "1.0", letterSpacing: "0.1em", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "headline-md": ["24px", { lineHeight: "1.3", fontWeight: "700" }],
        "body-md": ["16px", { lineHeight: "1.5", fontWeight: "400" }],
      },
    },
  },
  plugins: [],
};
